# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: prawn_shapes 1.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "prawn_shapes"
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Daniel Nelson"]
  s.date = "2015-04-14"
  s.description = "Adds additional vector shapes to Prawn"
  s.email = "daniel@populr.me"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/example_helper.rb",
    "examples/graphics/arc.rb",
    "examples/graphics/star.rb",
    "lib/prawn_shapes.rb",
    "lib/prawn_shapes/arc.rb",
    "lib/prawn_shapes/star.rb",
    "prawn_shapes.gemspec",
    "reference_pdfs/arc.pdf",
    "reference_pdfs/star.pdf",
    "spec/arc_spec.rb",
    "spec/spec_helper.rb",
    "spec/star_spec.rb"
  ]
  s.homepage = "https://github.com/Bluejade/prawn-shapes"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.3"
  s.summary = "Additional vector shapes for Prawn"
end

